config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  root 'home#index'
  resources :users, only: [:index, :show, :edit, :update]
  resources :artists, only: [:show, :new, :create, :edit, :update] do
    resources :favorites, only: [:index, :create, :destroy]
    member do
      get 'posts'
      get 'done_posts'
    end
    collection do
      get 'notyet' 
    end
  end
  resources :posts, except: [:index] do
    resources :likes, only: [:index, :create, :destroy]
    member do
      get 'done_show'
      get 'show_post'
      get 'show_house'
      delete 'destroy_post'
      delete 'done_destroy'
    end
    collection do
      get 'live_yet'
      get 'notyet' 
      get 'done'
      get 'not_yet' 
      get 'yet'
    end
  end
  resources :searches, only: [:index] do 
    collection do 
      get 'post_search' 
      get 'artist_search'
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :artist, counter_cache: :fav_count
  belongs_to :user
  validates_uniqueness_of :artist_id, scope: :user_id

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:create, :destroy]

  def index
    @artists = Favorite.where(user_id: current_user.id).page(params[:page]).per(12)
    @count = Favorite.where(user_id: current_user.id).count
  end

  def create
    @favorite = Favorite.create(user_id: current_user.id, artist_id: params[:artist_id])
  end


  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, artist_id: params[:artist_id])
    @favorite.destroy
  end

  
  private

  def set_favorite
    @artist = Artist.find(params[:artist_id])
  end


end

app/views/favorites/_artist.html.haml
- @artist = Artist.find_by(id: artist.artist.id)

.artist-box-2
  .artist-box-2__image
    = link_to artist_path(@artist.id) do 
      = image_tag @artist.image.url
  .artist-box-2__name
    = link_to artist_path(@artist.id) do 
      = @artist.name

app/views/favorites/_favorite.html.haml
- if @post.present?
  - if Favorite.find_by(user_id: current_user.id, artist_id: @post.artist.id).present?
    = link_to artist_favorite_path(@post.artist.id, current_user.id),class: 'show-main__container__top__right__unfollow', method: "DELETE", remote: true do
      フォロー中
  - else
    = link_to artist_favorites_path(@post.artist.id, current_user.id),class: 'show-main__container__top__right__follow', method: "POST", remote: true do
      フォロー

- else
  - if Favorite.find_by(user_id: current_user.id, artist_id: @artist.id).present?
    = link_to artist_favorite_path(@artist.id, current_user.id),class: 'show-main__container__top__right__unfollow', method: "DELETE", remote: true do
      フォロー中
  - else
    = link_to artist_favorites_path(@artist.id, current_user.id),class: 'show-main__container__top__right__follow', method: "POST", remote: true do
      フォロー

app/views/favorites/_my-artists.html.haml
.my-artists
  %h2.my-artists__title
    お気に入りアーティスト
  .my-artists__line

  - if @artists.present?
    %h2.my-artists__text
      フォロワー中のアーティストは
      = @count
      組です。

    .my-artists__main
      = render partial: 'artist', collection: @artists

    .my-pagenate
      = paginate(@artists)

  - else
    %h2.my-artists__text-2
      フォローしているアーティストはいません。

app/views/favorites/create.js.haml
$("#follow-container").html("#{escape_javascript(render partial: 'favorite', locals: {artist: @artist, favorite: @favorite})}")

app/views/favorites/destroy.js.haml
$("#follow-container").html("#{escape_javascript(render partial: 'favorite', locals: {artist: @artist, favorite: @favorite})}")

app/views/favorites/index.html.haml
.wrapper 
  = render 'shared/header'
  .mypage
    .mypage__container
      = render 'shared/side-bar'
      .right-main
        = render 'my-artists'
    = render 'shared/footer'