config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  root 'home#index'
  resources :users, only: [:index, :show, :edit, :update]
  resources :artists, only: [:show, :new, :create, :edit, :update] do
    resources :favorites, only: [:index, :create, :destroy]
    member do
      get 'posts'
      get 'done_posts'
    end
    collection do
      get 'notyet' 
    end
  end
  resources :posts, except: [:index] do
    resources :likes, only: [:index, :create, :destroy]
    member do
      get 'done_show'
      get 'show_post'
      get 'show_house'
      delete 'destroy_post'
      delete 'done_destroy'
    end
    collection do
      get 'live_yet'
      get 'notyet' 
      get 'done'
      get 'not_yet' 
      get 'yet'
    end
  end
  resources :searches, only: [:index] do 
    collection do 
      get 'post_search' 
      get 'artist_search'
    end
  end
end

app/views/shared/_apps.html.haml
.apps
  = link_to '#', class: "apps__appStore" do
    = image_tag "app_store.svg", size: "180x54", alt: "app_store"
  = link_to '#', class: "apps__googlePlay" do
    = image_tag "google_play.svg", size: "180x54", alt: "google_play"

app/views/shared/_delete-post.html.haml
.post-delete.top-delete
  .post-delete__top
    投稿を削除しますか？
  
  .post-delete__bottom
    .post-delete__bottom__left
      = link_to destroy_post_post_path(@post), method: :delete do
        はい

    .post-delete__bottom__right
      いいえ

app/views/shared/_delete.html.haml
.post-delete
  .post-delete__top
    投稿を削除しますか？
  
  .post-delete__bottom
    .post-delete__bottom__left
      - if @post.status == true
        = link_to post_path(@post), method: :delete do
          はい
      - if @post.status == false
        = link_to done_destroy_post_path(@post), method: :delete do
          はい


    .post-delete__bottom__right
      いいえ

app/views/shared/_detail-post.html.haml
.show-main__container__bottom
  .show-main__container__bottom__field
    .show-main__container__bottom__field__content
      .show-main__container__bottom__field__content__left
        LIVE予定日時

    .show-main__container__bottom__field__content
      .show-main__container__bottom__field__content__right
        = @post.date_time.strftime("%Y年%-m月%-d日 %-H時%-M分")

  .show-main__container__bottom__field
    .show-main__container__bottom__field__content
      .show-main__container__bottom__field__content__left
        LIVE予定時間

    .show-main__container__bottom__field__content
      .show-main__container__bottom__field__content__right
        = @post.how_long.name

  .show-main__container__bottom__field
    .show-main__container__bottom__field__content
      .show-main__container__bottom__field__content__left
        LIVE形式

    .show-main__container__bottom__field__content
      .show-main__container__bottom__field__content__right
        = @post.form.name

  .show-main__container__bottom__field
    .show-main__container__bottom__field__content
      .show-main__container__bottom__field__content__left
        会場名

    .show-main__container__bottom__field__content
      .show-main__container__bottom__field__content__right
        = @post.venue

  - if @post.fee.present?
    .show-main__container__bottom__field
      .show-main__container__bottom__field__content
        .show-main__container__bottom__field__content__left
          入場料金

      .show-main__container__bottom__field__content
        .show-main__container__bottom__field__content__right
          = @post.fee
          円

  .show-main__container__bottom__field
    .show-main__container__bottom__field__content
      .show-main__container__bottom__field__content__left
        最寄駅

    .show-main__container__bottom__field__content
      .show-main__container__bottom__field__content__right
        = @post.station
  
  .show-main__container__bottom__field
    .show-main__container__bottom__field__content
      .show-main__container__bottom__field__content__left
        会場の住所

    .show-main__container__bottom__field__content
      .show-main__container__bottom__field__content__right
        = @post.address

  .show-main__container__bottom__field
    .show-main__container__bottom__field__content
      .show-main__container__bottom__field__content__map
        会場の位置情報

  #map


.show-post__container__under
  - if user_signed_in? && current_user.id == @post.user.id
    .show-post__container__under__btns
      %span.show-post__container__under__btns__delete
        投稿を削除
      = link_to edit_post_path(@post.id) do
        LIVE情報を編集

  - elsif user_signed_in? 
    #like-container
      = render 'likes/like'

app/views/shared/_done_post.html.haml
= link_to show_post_post_path(done_post.id), class: 'index-lists' do
  .post
    .post__box
      %h2.post__box__text
        LIVEを開催した日
      %h2.post__box__content
        = done_post.date_time.strftime("%Y年 %m月 %d日")

    .post__box.row
      %h2.post__box__text
        LIVE形式
      %h2.post__box__content
        = done_post.form.name

    .post__box.row
      %h2.post__box__text
        会場名
      %h2.post__box__content
        = done_post.venue
    
  

app/views/shared/_first-introduction.html.haml
%section.introduction
  %h2.introduction__title 音楽をもっと身近に
  %p.introduction__text
    LIVErarianは誰でも簡単にライブ情報を発信、検索できる
    %br
    ライブ情報共有アプリです

  = render "shared/apps"

app/views/shared/_footer.html.haml
.footer
  .footer__container
    .footer__container__logo
      = link_to root_path do
        %span.left LIVE
        %span.right rarian
    .footer__container__box
      .footer__container__box__contents
        %h3.footer__container__box__contents__title  
          会社情報
        .footer__container__box__contents__content
          = link_to '#' do
            企業情報

        .footer__container__box__contents__content
          = link_to '#' do
            アクセス

        .footer__container__box__contents__content
          = link_to '#' do
            For the Record

      .footer__container__box__contents
        %h3.footer__container__box__contents__title  
          コミュニティ
        .footer__container__box__contents__content
          = link_to '#' do
            新着情報
            
        .footer__container__box__contents__content
          = link_to '#' do
            メールマガジン

        .footer__container__box__contents__content
          = link_to '#' do
            アーティスト向け
          
        .footer__container__box__contents__content
          = link_to '#' do
            投資家の皆さまへ

        .footer__container__box__contents__content
          = link_to '#' do
            無料モバイルアプリ

      .footer__container__box__contents
        %h3.footer__container__box__contents__title  
          その他
        .footer__container__box__contents__content
          = link_to '#' do
            お問い合わせ
            
        .footer__container__box__contents__content
          = link_to '#' do
            利用規約

        .footer__container__box__contents__content
          = link_to '#' do
            プライバシーポリシー

        .footer__container__box__contents__content
          = link_to '#' do
            個人情報保護方針
    
    .footer__container__sns
      %ul.footer__container__sns__lists
        %li.footer__container__sns__lists__list
          = link_to '#' do
            %i.fab.fa-instagram

        %li.footer__container__sns__lists__list
          = link_to '#' do
            %i.fab.fa-twitter

        %li.footer__container__sns__lists__list
          = link_to '#' do
            %i.fab.fa-facebook-f
            
    .footer__container__bottoms
      %ul.footer__container__bottoms__lists
        %li.footer__container__bottoms__lists__list
          = link_to '#' do
            法的措置
        %li.footer__container__bottoms__lists__list
          = link_to '#' do
            プライバシーセンター
        %li.footer__container__bottoms__lists__list
          = link_to '#' do
            Cookies
        %li.footer__container__bottoms__lists__list
          = link_to '#' do
            広告について
        %li.footer__container__bottoms__lists__list.right
          © 2020 LIVErarian
        

app/views/shared/_header.html.haml
.header
  .header__box
    .header__box__logo
      = link_to root_path do
        %span.left LIVE
        %span.right rarian
    .header__box__search-hidden
      = search_form_for(@q, url: post_search_searches_path)do |f|
        = f.search_field :artist_name_or_station_or_venue_or_address_cont, placeholder: "キーワード検索　（アーティスト名、最寄駅、会場名などから検索）", class: 'header-input'
        = button_tag 'search', name: nil, id: "header-search" do
          post
      = search_form_for(@p, url: artist_search_searches_path)do |f|
        = f.search_field :name_or_active_place_cont, placeholder: "キーワード検索　（アーティスト名、活動拠点などから検索）", class: 'header-input'
        = button_tag 'search', name: nil, id: "header-search-artist" do
          artist

    - if user_signed_in?
      %nav.header__box__container
        %ul.header__box__container__lists
          %li.header__box__container__lists__list
            = link_to root_path do
              Top
              
          %li.header__box__container__lists__list
            .header__box__container__lists__list__find
              Find

          %li.header__box__container__lists__list
            - if @artist_info.present? 
              = link_to new_post_path do
                Post
            - else
              = link_to notyet_posts_path do
                Post

          %li.header__box__container__lists__list--line

          - if @artist_info.present? 
            %li.header__box__container__lists__list
              = link_to users_path do
                = image_tag @artist_info.image.url, class: 'header-icon'

            %li.header__box__container__lists__list.profile 
              = link_to users_path, class: 'header-profile' do
                プロフィール

          - else
            %li.header__box__container__lists__list
              = link_to users_path do
                プロフィール


    - else
      %nav.header__box__container
        %ul.header__box__container__lists
          %li.header__box__container__lists__list
            = link_to root_path do
              Top
          %li.header__box__container__lists__list
            .header__box__container__lists__list__find
              Find
          %li.header__box__container__lists__list
            = link_to new_post_path do
              Post
          %li.header__box__container__lists__list--line

          %li.header__box__container__lists__list
            = link_to new_user_registration_path do
              新規登録
          %li.header__box__container__lists__list
            = link_to new_user_session_path do
              ログイン

app/views/shared/_new.html.haml
.artist-box
  .artist-box__image
    = link_to artist_path(new.id) do 
      = image_tag new.image.url
  .artist-box__name
    = link_to artist_path(new.id) do 
      = new.name

app/views/shared/_show-artist.html.haml
.show-main__container__top
  .show-main__container__top__left
    = link_to artist_path(@artist.id) do 
      = image_tag @artist.image.url

  .show-main__container__top__right
    %h2.show-main__container__top__right__name
      = link_to artist_path(@artist.id) do 
        = @artist.name

    %h2.show-main__container__top__right__text
      = link_to posts_artist_path(@artist.id) do
        開催予定のLIVE (
        = @count_yet
        件)
    %h2.show-main__container__top__right__text
      = link_to done_posts_artist_path(@artist.id) do
        過去に開催したLIVE (
        = @count_done
        件)

    - if user_signed_in? && current_user.id == @artist.user.id
      = link_to edit_artist_path(@artist.id), class: "edit" do
        アーティスト情報を編集

    - elsif user_signed_in? 
      #follow-container
        = render 'favorites/favorite'

app/views/shared/_show-posts.html.haml
.show-main__container__top
  .show-main__container__top__left
    = link_to artist_path(@post.artist_id) do 
      = image_tag @post.artist.image.url

  .show-main__container__top__right
    %h2.show-main__container__top__right__name
      = link_to artist_path(@post.artist_id) do 
        = @post.artist.name
    %h2.show-main__container__top__right__text
      = link_to posts_artist_path(@post.artist_id) do
        開催予定のLIVE (
        = @count_yet
        件)
    %h2.show-main__container__top__right__text
      = link_to done_posts_artist_path(@post.artist_id) do
        過去に開催したLIVE (
        = @count_done
        件)

    - if user_signed_in? && current_user.id == @post.user.id
      = link_to edit_artist_path(@post.artist_id), class: "edit" do
        アーティスト情報を編集

    - elsif user_signed_in? 
      #follow-container
        = render 'favorites/favorite'

app/views/shared/_side-bar.html.haml
%nav.side-bar
  %ul.side-bar__lists

    %li.bar.show-1
    %li.side-bar__lists__list.hid
      = link_to users_path do
        %i.fas.fa-home
        アカウント情報
        %i.fas.fa-chevron-right

    %li.bar.show-2
    %li.side-bar__lists__list.hid
      = link_to edit_user_path(current_user) do
        %i.fas.fa-user-cog
        プロフィールを編集
        %i.fas.fa-chevron-right

    %li.bar.show-3
    %li.side-bar__lists__list.hid
      = link_to artist_favorites_path(current_user.id) do
        %i.fas.fa-star
        お気に入りアーティスト
        %i.fas.fa-chevron-right

    %li.bar.show-4
    %li.side-bar__lists__list.hid
      = link_to post_likes_path(current_user.id ) do
        %i.fas.fa-headphones
        My LIVE
        %i.fas.fa-chevron-right

    %li.bar.show-5
    %li.side-bar__lists__list.hid
      - if @artist_info.present? 
        = link_to edit_artist_path(@artist_info.id) do
          %i.fas.fa-address-card
          アーティスト情報を編集
          %i.fas.fa-chevron-right
      - else
        = link_to notyet_artists_path do
          %i.fas.fa-address-card
          アーティスト情報を編集
          %i.fas.fa-chevron-right

    %li.bar.show-6
    %li.side-bar__lists__list.hid
      - if @artist_info.present? 
        = link_to new_post_path do
          %i.fas.fa-podcast
          LIVE情報を投稿
          %i.fas.fa-chevron-right
      - else
        = link_to notyet_posts_path do
          %i.fas.fa-podcast
          LIVE情報を投稿
          %i.fas.fa-chevron-right

    %li.bar.show-7.hid
    %li.side-bar__lists__list
      - if @artist_info.present? 
        = link_to live_yet_posts_path do
          %i.fas.fa-microphone
          開催予定のLIVE
          %i.fas.fa-chevron-right
      - else
        = link_to not_yet_posts_path do
          %i.fas.fa-microphone
          開催予定のLIVE
          %i.fas.fa-chevron-right

    %li.bar.show-8.hid
    %li.side-bar__lists__list
      - if @artist_info.present? 
        = link_to done_posts_path do
          %i.fas.fa-compact-disc
          過去に開催したLIVE
          %i.fas.fa-chevron-right
      - else
        = link_to yet_posts_path do
          %i.fas.fa-compact-disc    
          過去に開催したLIVE
          %i.fas.fa-chevron-right

    %li.side-bar__lists__list.logout-show
      .side-bar__lists__list__logout
        %i.fas.fa-sign-out-alt
        ログアウト
        %i.fas.fa-chevron-right

= render "shared/logout"

app/views/shared/_today.html.haml
= link_to show_post_post_path(today.id) do 
  .posts-box 
    .posts-box__top
      .posts-box__top__image
        = image_tag today.artist.image.url

      .posts-box__top__right
        %h2.posts-box__top__right__sub
          アーティスト名
        %h2.posts-box__top__right__text
          = today.artist.name
        %h2.posts-box__top__right__sub
          LIVE開始時刻
        %h2.posts-box__top__right__text
          = today.date_time.strftime("%-m月%-d日 %-H時%-M分")
        %h2.posts-box__top__right__sub
          LIVE予定時間
        %h2.posts-box__top__right__text
          = today.how_long.name
        - if today.now_on == false
          .posts-box-2__top__right__now-on
            開催中
        - elsif today.status == false
          .posts-box-2__top__right__done-live
            終了済
        - else 
          .posts-box-2__top__right__yet
            開催前


    .posts-box__bottom
      .posts-box__bottom__box
        .posts-box__bottom__box__left
          最寄駅
        .posts-box__bottom__box__right
          = today.station
      .posts-box__bottom__box
        .posts-box__bottom__box__left
          会場名
        .posts-box__bottom__box__right
          = today.venue

app/views/shared/_today_house.html.haml
= link_to show_house_post_path(today_house.id) do 
  .posts-box 
    .posts-box__top
      .posts-box__top__image
        = image_tag today_house.artist.image.url

      .posts-box__top__right
        %h2.posts-box__top__right__sub
          アーティスト名
        %h2.posts-box__top__right__text
          = today_house.artist.name
        %h2.posts-box__top__right__sub
          LIVE開始時刻
        %h2.posts-box__top__right__text
          = today_house.date_time.strftime("%-m月%-d日 %-H時%-M分")
        %h2.posts-box__top__right__sub
          LIVE予定時間
        %h2.posts-box__top__right__text
          = today_house.how_long.name
        - if today_house.now_on == false
          .posts-box-2__top__right__now-on
            開催中
        - elsif today_house.status == false
          .posts-box-2__top__right__done-live
            終了済
        - else 
          .posts-box-2__top__right__yet
            開催前


    .posts-box__bottom
      .posts-box__bottom__box
        .posts-box__bottom__box__left
          最寄駅
        .posts-box__bottom__box__right
          = today_house.station
      .posts-box__bottom__box
        .posts-box__bottom__box__left
          会場名
        .posts-box__bottom__box__right
          = today_house.venue