config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  root 'home#index'
  resources :users, only: [:index, :show, :edit, :update]
  resources :artists, only: [:show, :new, :create, :edit, :update] do
    resources :favorites, only: [:index, :create, :destroy]
    member do
      get 'posts'
      get 'done_posts'
    end
    collection do
      get 'notyet' 
    end
  end
  resources :posts, except: [:index] do
    resources :likes, only: [:index, :create, :destroy]
    member do
      get 'done_show'
      get 'show_post'
      get 'show_house'
      delete 'destroy_post'
      delete 'done_destroy'
    end
    collection do
      get 'live_yet'
      get 'notyet' 
      get 'done'
      get 'not_yet' 
      get 'yet'
    end
  end
  resources :searches, only: [:index] do 
    collection do 
      get 'post_search' 
      get 'artist_search'
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def index
  end
  
  def post_search
    if params[:q][:status_in] == '1'
      @search_post = Post.where(now_on: '1').ransack(params[:q])
      set_post

    elsif params[:q][:status_in].present?
      @search_post = Post.ransack(params[:q])
      set_post

    else
      @search_post = Post.where(status: '1').ransack(params[:q])
      set_post
    end
  end


  def artist_search
    @search_artist = Artist.ransack(params[:q])
    @artists = @search_artist.result.order(id: "DESC").page(params[:page])
  end

  private

  def set_post
    @posts = @search_post.result.order(date_time: "ASC").page(params[:page])
  end

end

app/views/searches/_artist-search.html.haml
.search
  .search__top
    = search_form_for(@p, url: artist_search_searches_path)do |f|
      = f.search_field :name_or_active_place_cont, placeholder: "キーワード検索　（アーティスト名、活動拠点などから検索）", class: 'input-default'
      = button_tag 'search', name: nil, class: "search-btn" do
        %i.fas.fa-search


  .search__bottom
    .search__bottom__left__which
      .post-search.re-gray
        LIVE検索
      .artist-search.re-green
        アーティスト検索

    - if params[:q][:name_or_active_place_cont].empty?
      %p.search__bottom__nil
        アーティスト一覧

    - elsif @artists.present?
      .artist-result
        %h2.search__bottom__right__head
          = @p.name_or_active_place_cont
          %span.search__bottom__right__head__text
            の検索結果
        .search__bottom__right__number
          ="1-#{@artists.count}件表示"
          
    - else 
      .artist-result
        %h2.search__bottom__right__head
          = @p.name_or_active_place_cont
          %span.search__bottom__right__head__text
            の検索結果
        .search__bottom__right__text-2
          該当するアーティストが見つかりません。検索条件を変えて、再度お試しください。


  - if params[:q][:name_or_active_place_cont].empty?
    .search__artists.row 
      = render partial: 'artist', collection: @artists_all

  - elsif @artists.present?
    .search__artists 
      = render partial: 'artist', collection: @artists

  - else 
    .search__artists 
      = render partial: 'artist', collection: @artists_all
      

app/views/searches/_artist.html.haml
.artist-box
  .artist-box__image
    = link_to artist_path(artist.id) do 
      = image_tag artist.image.url
  .artist-box__name
    = link_to artist_path(artist.id) do 
      = artist.name

app/views/searches/_index.html.haml
.search
  .mk
    .search__bottom__left__which.mkr
      .post-search
        LIVE検索
      .artist-search
        アーティスト検索
    
    .map-search
      #map

app/views/searches/_post-left.html.haml
.search__bottom__left
  = search_form_for(@q, url: post_search_searches_path)do |f|
    .search__bottom__left__which
      .post-search
        LIVE検索
      .artist-search
        アーティスト検索
    
    .search__bottom__left__locate
      = link_to searches_path do
        位置情報から検索する

    .search__bottom__left__form
      %h2.search__bottom__left__form__title
        詳細検索
      .search__bottom__left__form__group
        .search__bottom__left__form__group__label
          %i.fas.fa-plus
          %span キーワードを追加する
        = f.search_field :artist_name_or_station_or_venue_or_address_cont, placeholder: "キーワード検索を追加", class: 'input-left'

      .search__bottom__left__form__group
        .search__bottom__left__form__group__label
          %i.fas.fa-guitar
          %span LIVE形式から探す
        = f.collection_select :form_id_eq, Form.all, :id, :name, include_blank: 'すべて'
        %i.fas.fa-chevron-down
        .back-white

      .search__bottom__left__form__group
        .search__bottom__left__form__group__label
          %i.fas.fa-calendar-alt
          %span 開催日時
        =f.date_select :date_time_gteq, {}, class: 'date-select'
        .back-white-2
        .back-white-2.second
        .back-white-2.third
        .back-white-3
        .back-white-3.second
        .back-white-3.third
        %i.fas.fa-chevron-down.top-left
        %i.fas.fa-chevron-down.top-right
        %i.fas.fa-chevron-down.bottom-left
        %i.fas.fa-chevron-down.bottom-right
        %span.year　年
        %span.year.sita　年
        %span.date　日
        %span.date.sita　日

        .aff
          %p.from-to 〜
        =f.date_select :date_time_lteq, selected: Date.today + 1.month, class: 'date-select'



      .search__bottom__left__form__group
        .search__bottom__left__form__group__label
          %i.fas.fa-satellite-dish
          %span LIVE状況
        .search__bottom__left__form__group__box
          .search__bottom__left__form__group__box__content
            %input{type:'checkbox', value: "1", name: "q[status_in]", id: "form-1"}
            %label.lbl{for: 'form-1'}
              開催前
          .search__bottom__left__form__group__box__content.now-on
            %input{type:'checkbox', value: "0", name: "q[now_on_in]", id: "form-2"}
            %label.lbl{for: 'form-2'}
              開催中
          .search__bottom__left__form__group__box__content
            %input{type:'checkbox', value: "0", name: "q[status_in]", id: "form-3"}
            %label.lbl{for: 'form-3'}
              終了済   
      
      .search__bottom__left__form__btn
        = f.submit "クリア", type: :reset, class: "clear-btn"
        = f.submit "完了", class: "comp-btn"

app/views/searches/_post-right.html.haml
.search__bottom__right

  - if params[:q][:artist_name_or_station_or_venue_or_address_cont].empty? && @posts.present?
    %h2.search__bottom__right__nil
      LIVE一覧
    .search__bottom__right__main 
      = render partial: 'post', collection: @posts

  -elsif params[:q][:artist_name_or_station_or_venue_or_address_cont].empty?
    %h2.search__bottom__right__nil
      LIVE一覧
    .search__bottom__right__text-2
      該当するLIVEが見つかりません。検索条件を変えて、再度お試しください。
    .search__bottom__right__main 
      = render partial: 'post', collection: @posts_all


  -elsif @posts.present?
    %h2.search__bottom__right__head
      = @q.artist_name_or_station_or_venue_or_address_cont
      %span.search__bottom__right__head__text
        の検索結果
    .search__bottom__right__number
      ="1-#{@posts.count}件表示"
    .search__bottom__right__main 
      = render partial: 'post', collection: @posts

  -else
    %h2.search__bottom__right__head
      = @q.artist_name_or_station_or_venue_or_address_cont
      %span.search__bottom__right__head__text
        の検索結果
    .search__bottom__right__text-2
      該当するLIVEが見つかりません。検索条件を変えて、再度お試しください。
    .search__bottom__right__main 
      = render partial: 'post', collection: @posts_all

app/views/searches/_post-search.html.haml
.search
  .search__top
    = search_form_for(@q, url: post_search_searches_path)do |f|
      = f.search_field :artist_name_or_station_or_venue_or_address_cont, placeholder: "キーワード検索　（アーティスト名、最寄駅、会場名などから検索）", class: 'input-default'
      = button_tag 'search', name: nil, class: "search-btn" do
        %i.fas.fa-search


  .search__bottom
    = render 'post-left'


    = render 'post-right'

app/views/searches/_post.html.haml
= link_to show_post_post_path(post.id) do 
  .posts-box 
    .posts-box__top
      .posts-box__top__image
        = image_tag post.artist.image.url

      .posts-box__top__right
        %h2.posts-box__top__right__sub
          アーティスト名
        %h2.posts-box__top__right__text
          = post.artist.name
        %h2.posts-box__top__right__sub
          LIVE開始時刻
        %h2.posts-box__top__right__text
          = post.date_time.strftime("%-m月%-d日 %-H時%-M分")
        %h2.posts-box__top__right__sub
          LIVE予定時間
        %h2.posts-box__top__right__text
          = post.how_long.name
        - if post.now_on == false
          .posts-box-2__top__right__now-on
            開催中
        - elsif post.status == false
          .posts-box-2__top__right__done-live
            終了済
        - else 
          .posts-box-2__top__right__yet
            開催前

    .posts-box__bottom
      .posts-box__bottom__box
        .posts-box__bottom__box__left
          最寄駅
        .posts-box__bottom__box__right
          = post.station
      .posts-box__bottom__box
        .posts-box__bottom__box__left
          会場名
        .posts-box__bottom__box__right
          = post.venue

app/views/searches/artist_search.html.haml
.wrapper 
  = render 'shared/header'
  = render 'artist-search'
  = render 'shared/footer'

app/views/searches/index.html.haml
.wrapper 
  = render 'shared/header'
  = render 'index'
  = render 'shared/footer'

app/views/searches/post_search.html.haml
.wrapper 
  = render 'shared/header'
  = render 'post-search'
  = render 'shared/footer'