config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  root 'home#index'
  resources :users, only: [:index, :show, :edit, :update]
  resources :artists, only: [:show, :new, :create, :edit, :update] do
    resources :favorites, only: [:index, :create, :destroy]
    member do
      get 'posts'
      get 'done_posts'
    end
    collection do
      get 'notyet' 
    end
  end
  resources :posts, except: [:index] do
    resources :likes, only: [:index, :create, :destroy]
    member do
      get 'done_show'
      get 'show_post'
      get 'show_house'
      delete 'destroy_post'
      delete 'done_destroy'
    end
    collection do
      get 'live_yet'
      get 'notyet' 
      get 'done'
      get 'not_yet' 
      get 'yet'
    end
  end
  resources :searches, only: [:index] do 
    collection do 
      get 'post_search' 
      get 'artist_search'
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  geocoded_by :address
  after_validation :geocode

  belongs_to :user
  belongs_to :artist
  belongs_to_active_hash :form
  belongs_to_active_hash :how_long

  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user

  validates :date_time, :how_long_id, :form_id,:address, :venue, :station, presence: true

  def self.search(search)
    return Post.all unless search
    Post.where('name LIKE(?)', "%#{search}%")
  end

  # validate :date_before_start


  # def date_before_start
  #   errors.add(:date_time, "は現在時刻以降のものを選択してください。") if
  #   date_time < Time.now
  # end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :new, :create, :edit, :update, :destroy, :destroy_post,:done_destroy, :live_yet, :notyet]
  before_action :set_post, only: [:show, :show_post, :show_house, :edit, :update, :destroy, :destroy_post, :done_destroy, :done_show]
  before_action :artist_id, only: [:edit, :create, :update]
  before_action :count_post, only: [:show_post, :show_house]
  before_action :gon_set, only: [:show, :done_show, :show_post, :show_house]

  def show
  end


  def done_show
  end


  def show_post
  end


  def show_house
  end


  def new
    if current_user.artist.present?
      @post = Post.new
    else 
      redirect_back(fallback_location: users_path)
    end
  end


  def create
    @artist = Artist.find_by(user_id: current_user.id)
    @post = Post.new(post_params)
    if @post.save
      redirect_status
    else
      render :new
    end
  end


  def edit 
    if @post.status == false
      redirect_to done_show_post_path(@post.id)
    end
  end


  def update
    if current_user.id == @post.user_id && @post.update(post_params)
      redirect_status
    else
      render :edit
    end
  end


  def destroy
    if current_user.id == @post.user_id && @post.destroy
      redirect_to live_yet_posts_path
    else
      redirect_to post_path(@post.id)
    end
  end


  def destroy_post
    if current_user.id == @post.user_id && @post.destroy
      redirect_to root_path
    else
      redirect_to post_path(@post.id)
    end
  end


  def done_destroy
    if current_user.id == @post.user_id && @post.destroy
      redirect_to done_posts_path
    else
      redirect_to done_destroy_post_path(@post.id)
    end
  end


  def live_yet    
    @posts = Post.where(user_id: current_user.id, status: '1').order(date_time: "ASC").page(params[:page]).per(6)
    @count = Post.where(user_id: current_user.id, status: '1').length
  end


  def done
    @dones = Post.where(user_id: current_user.id, status: '0').order(date_time: "ASC").page(params[:page]).per(6)
    @count = Post.where(user_id: current_user.id, status: '0').length

  end


  def notyet
  end


  def not_yet
  end


  def yet
  end


  private

  def post_params
    params.require(:post).permit(:station, :address, :fee, :venue, :date_time, :form_id, :how_long_id ).merge(user_id: current_user.id, artist_id: @artist.id)
  end


  def set_post
    @post = Post.find(params[:id])
  end


  def artist_id
    @artist = Artist.find_by(user_id: current_user.id)
  end


  def redirect_status
    if @post.status == true
      redirect_to post_path(@post.id)
    elsif @post.status == false
      redirect_to done_show_post_path(@post.id)
    end
  end


  def count_post
    @count_yet = Post.where(user_id: @post.user_id, status: '1').length
    @count_done = Post.where(user_id: @post.user_id, status: '0').length
  end


  def gon_set
    gon.latitude = @post.latitude
    gon.longitude = @post.longitude
    gon.venue = @post.venue
  end

end

app/views/posts/_done.html.haml
.done
  .done__top
    %h1.done__top__text
      過去に開催したLIVE
    .done__top__line

  
  - if  @dones.present?
    .done__count
      = @count
      件のLIVEを過去に開催しました。

  .done__main
    - if  @dones.present?
      = render partial: 'shared/done', collection: @dones

    - else
      .done__main__yet
        %h2.done__main__yet__text
          過去に開催したLIVEはありません。
        
        .done__main__yet__box
          = link_to new_post_path do
            LIVE情報を投稿
    
  .my-pagenate
    = paginate(@dones)

  

app/views/posts/_edit.html.haml
.new-post
  %h2.new-post__text
    LIVE情報を投稿

  .new-post__container
    = form_with model: @post, local: true do |f|
      .frame
        %label.new-post__container__field
          .tpnhk
            %span.title LIVE予定日時
            %span.new-post__container__require 必須

          =f.datetime_select :date_time, {}, class: 'date-form'
          %i.fas.fa-chevron-down.bar-1
          %i.fas.fa-chevron-down.bar-2
          %i.fas.fa-chevron-down.bar-3
          %i.fas.fa-chevron-down.bar-4
          %i.fas.fa-chevron-down.bar-5
          %n.year 年
          %n.date 日
          %n.hour 時
          %n.minute 分
        = render partial: 'users/shared/error_messages', locals: { column: :date_time, input: @post }
          
      .frame
        %label.new-post__container__field
          .tpnhk
            %span.title.row LIVE予定時間
            %span.new-post__container__require-2 必須

          = f.collection_select :how_long_id, HowLong.all, :id, :name, {prompt: "--"}, {class: 'selector'}
          %i.fas.fa-chevron-down.bar-6
        = render partial: 'users/shared/error_messages', locals: { column: :how_long_id, input: @post }

      .form-box
        .form-content.first
          %label.new-post__container__field
            .tpnhk-mgin
              %span.title.row LIVE形式
              %span.new-post__container__require-3 必須
            = f.collection_select :form_id, Form.all, :id, :name, {prompt: "--"}, {class: 'selector active-js'}
            %i.fas.fa-chevron-down.bar-7
          = render partial: 'users/shared/error_messages', locals: { column: :form_id, input: @post }

        .form-content
          %label.new-post__container__field
            .tpnhk
              %span.title.row 最寄駅
              %span.new-post__container__require-4 必須
            = f.text_field :station, placeholder: '最寄駅', class:'station-form'
          = render partial: 'users/shared/error_messages', locals: { column: :station, input: @post }

        .form-content.not-active
          %label.new-post__container__field
            .tpnhk
              %span.row 入場料金
              %span.new-post__container__require-5 任意
            = f.text_field :fee,type: 'number', placeholder: '入場料金', class:'price-form'
            %span.yen 円


      %label.new-post__container__field
        .tpnhk
          %span.row 会場名
          %span.new-post__container__require-6 必須
        = f.text_field :venue, placeholder: '会場名', class:'venue-form'
      = render partial: 'users/shared/error_messages', locals: { column: :venue, input: @post }

      %label.new-post__container__field
        .tpnhk-space
          %span.row 会場の住所
          %span.new-post__container__require-6 必須
        = f.text_field :address, placeholder: '住所　（例）渋谷区1-2-34', class:'venue-form'
      = render partial: 'users/shared/error_messages', locals: { column: :address, input: @post }


      .new-post__container__btns
        = link_to users_path do
          キャンセル
        = f.submit "投稿する", type: 'submit', class: 'btn'

app/views/posts/_live-yet.html.haml
.live-yet
  .live-yet__top
    %h1.live-yet__top__text
      開催予定のLIVE
    .live-yet__top__line

  
  - if  @posts.present?
    .live-yet__count
      = @count
      件のLIVEを開催する予定です。

  .live-yet__main
    - if  @posts.present?
      = render partial: 'shared/post', collection: @posts

    - else
      .live-yet__main__yet
        %h2.live-yet__main__yet__text
          現在開催を予定しているLIVEはありません。
        
        .live-yet__main__yet__box
          = link_to new_post_path do
            LIVE情報を投稿

  .my-pagenate
    = paginate(@posts)

  

app/views/posts/_new-post.html.haml
.new-post
  %h2.new-post__text
    LIVE情報を投稿

  .new-post__container
    = form_with model: @post, local: true do |f|
      .frame
        %label.new-post__container__field
          .tpnhk
            %span.title LIVE予定日時
            %span.new-post__container__require 必須

          =f.datetime_select :date_time, {}, class: 'date-form'
          %i.fas.fa-chevron-down.bar-1
          %i.fas.fa-chevron-down.bar-2
          %i.fas.fa-chevron-down.bar-3
          %i.fas.fa-chevron-down.bar-4
          %i.fas.fa-chevron-down.bar-5
          %n.year 年
          %n.date 日
          %n.hour 時
          %n.minute 分
        = render partial: 'users/shared/error_messages', locals: { column: :date_time, input: @post }
          
      .frame
        %label.new-post__container__field
          .tpnhk
            %span.title.row LIVE予定時間
            %span.new-post__container__require-2 必須

          = f.collection_select :how_long_id, HowLong.all, :id, :name, {prompt: "--"}, {class: 'selector'}
          %i.fas.fa-chevron-down.bar-6
        = render partial: 'users/shared/error_messages', locals: { column: :how_long_id, input: @post }

      .form-box
        .form-content.first
          %label.new-post__container__field
            .tpnhk-mgin
              %span.title.row LIVE形式
              %span.new-post__container__require-3 必須
            = f.collection_select :form_id, Form.all, :id, :name, {prompt: "--"}, {class: 'selector active-js'}
            %i.fas.fa-chevron-down.bar-7
          = render partial: 'users/shared/error_messages', locals: { column: :form_id, input: @post }

        .form-content
          %label.new-post__container__field
            .tpnhk
              %span.title.row 最寄駅
              %span.new-post__container__require-4 必須
            = f.text_field :station, placeholder: '最寄駅', class:'station-form'
          = render partial: 'users/shared/error_messages', locals: { column: :station, input: @post }

        .form-content.not-active
          %label.new-post__container__field
            .tpnhk
              %span.row 入場料金
              %span.new-post__container__require-5 任意
            = f.text_field :fee,type: 'number', placeholder: '入場料金', class:'price-form'
            %span.yen 円


      %label.new-post__container__field
        .tpnhk
          %span.row 会場名
          %span.new-post__container__require-6 必須
        = f.text_field :venue, placeholder: '会場名', class:'venue-form'
      = render partial: 'users/shared/error_messages', locals: { column: :venue, input: @post }

      %label.new-post__container__field
        .tpnhk-space
          %span.row 会場の住所
          %span.new-post__container__require-6 必須
        = f.text_field :address, placeholder: '住所　（例）渋谷区1-2-34', class:'venue-form'
      = render partial: 'users/shared/error_messages', locals: { column: :address, input: @post }


      .new-post__container__btns
        = link_to users_path do
          キャンセル
        = f.submit "投稿する", type: 'submit', class: 'btn'

app/views/posts/_notyet-post.html.haml
.not-yet__container
  %h2.not-yet__container__text
    LIVE情報を投稿

  %h3.not-yet__container__text-2
    アーティスト情報がまだ登録されていません。

  .not-yet__container__box
    = link_to new_artist_path do
      アーティスト情報を登録

app/views/posts/_show-house.html.haml
= render "shared/delete-post"
.show-post
  .back-non
  .show-post__container
    %h2.show-post__container__title
      LIVE情報
    .show-post__container__line

    = render 'shared/show-posts'

    = render 'shared/detail-post'

app/views/posts/_show.html.haml
.show-live
  %h1.show-live__text
    LIVE情報
  .show-live__line


  .show-live__info
    .show-live__info__field
      .show-live__info__field__content
        .show-live__info__field__content__left
          - if @post.status == true
            LIVE予定日時
          - else 
            LIVEを開催した日時
      .show-live__info__field__content
        .show-live__info__field__content__right
          = @post.date_time.strftime("%Y年%-m月%-d日 %-H時%-M分")


    .show-live__info__field
      .show-live__info__field__content
        .show-live__info__field__content__left
          - if @post.status == true
            LIVE予定時間
          - else 
            LIVE時間
      .show-live__info__field__content
        .show-live__info__field__content__right
          = @post.how_long.name


    .show-live__info__field
      .show-live__info__field__content
        .show-live__info__field__content__left
          LIVE形式
      .show-live__info__field__content
        .show-live__info__field__content__right
          = @post.form.name


    .show-live__info__field
      .show-live__info__field__content
        .show-live__info__field__content__left
          会場名
      .show-live__info__field__content
        .show-live__info__field__content__right
          = @post.venue

    - if @post.fee.present?
      .show-live__info__field
        .show-live__info__field__content
          .show-live__info__field__content__left
            入場料金
        .show-live__info__field__content
          .show-live__info__field__content__right
            = @post.fee
            円

    .show-live__info__field
      .show-live__info__field__content
        .show-live__info__field__content__left
          最寄駅
      .show-live__info__field__content
        .show-live__info__field__content__right
          = @post.station
          
    .show-live__info__field
      .show-live__info__field__content
        .show-live__info__field__content__left
          会場の住所
      .show-live__info__field__content
        .show-live__info__field__content__right
          = @post.address

    .show-live__info__field
      .show-live__info__field__content
        .show-live__info__field__content__bottom
          会場の位置情報
    #map
    

    .show-live__info__btns
      - if @post.status == true
        .show-live__info__btns__btn
          = link_to edit_post_path(@post.id) do
            LIVE情報を編集

      .show-live__info__btns__btn.delete-post
        投稿を削除

      -# - if @post.status == true
      -#   .show-live__info__btns__btn.cancel
      -#     LIVEを中止する

= render "shared/delete"
.background

app/views/posts/_yet.html.haml
.not-yet__container
  %h2.not-yet__container__text
    過去に開催したLIVE

  %h3.not-yet__container__text-2
    アーティスト情報がまだ登録されていません。

  .not-yet__container__box
    = link_to new_artist_path do
      アーティスト情報を登録

app/views/posts/done.html.haml
.wrapper 
  = render 'shared/header'
  .mypage
    .mypage__container
      = render 'shared/side-bar'
      .right-main
        = render 'done'
    = render 'shared/footer'

app/views/posts/edit.html.haml
.wrapper 
  = render 'shared/header'
  .mypage
    .mypage__container
      = render 'shared/side-bar'
      .right-main
        = render 'edit'
    = render 'shared/footer'
    

app/views/posts/notyet.html.haml
.wrapper 
  = render 'shared/header'
  .mypage
    .mypage__container
      = render 'shared/side-bar'
      .right-main
        .not-yet
          = render 'notyet-post'
    = render 'shared/footer'

app/views/posts/show.html.haml
.wrapper 
  = render 'shared/header'
  .mypage
    .mypage__container
      = render 'shared/side-bar'
      .right-main
        = render 'show'
    = render 'shared/footer'

app/views/posts/show_house.html.haml
.wrapper 
  = render 'shared/header'
  = render 'show-house'
  = render 'shared/footer'

app/views/posts/show_post.html.haml
.wrapper 
  = render 'shared/header'
  = render 'show-post'
  = render 'shared/footer'